-- 테이블 삭제
 DROP TABLE IF EXISTS HY_CHMP;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_CHMP
 (
	CHMP_NO INT NOT NULL AUTO_INCREMENT COMMENT '챔피언번호',
    CHMP_NAME VARCHAR(20) NOT NULL COMMENT '챔피언명',
    CHMP_KRNM VARCHAR(20) NOT NULL COMMENT '챔피언명(KR)',
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_CHMP_PK PRIMARY KEY(CHMP_NO)
 ) COMMENT 'HY 챔피언';
 
 ALTER TABLE HY_CHMP AUTO_INCREMENT = 800000;

DESC HY_CHMP;
SHOW INDEX FROM HY_CHMP;

SELECT * FROM HY_CHMP;