-- 테이블 삭제
 DROP TABLE IF EXISTS HY_CHMP_ATCH;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_CHMP_ATCH
 (
	CHMP_ATCH_SEQ INT NOT NULL AUTO_INCREMENT COMMENT '챔피언첨부파일 SEQ',
    CHMP_NO INT NOT NULL COMMENT '챔피언번호',
    CHMP_ATCH_NO TINYINT NOT NULL COMMENT '챔피언첨부파일번호',
    FILE_TYPE VARCHAR(20) NOT NULL COMMENT '파일타입', -- 공통코드
    FILE_PATH VARCHAR(500) NOT NULL COMMENT '파일경로',
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_CHMP_ATCH_PK PRIMARY KEY(CHMP_ATCH_SEQ),
    INDEX HY_CHMP_ATCH_IDX1 (CHMP_NO)
 ) COMMENT 'HY 챔피언첨부파일';
 
 ALTER TABLE HY_CHMP_ATCH AUTO_INCREMENT = 100000;

DESC HY_CHMP_ATCH;
SHOW INDEX FROM HY_CHMP_ATCH;

SELECT * FROM HY_CHMP_ATCH;