-- 테이블 삭제
 DROP TABLE IF EXISTS HY_LGUE;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_LGUE
 (
	LGUE_NO INT NOT NULL AUTO_INCREMENT COMMENT '리그번호',
    LGUE_GRUP VARCHAR(20) NOT NULL COMMENT '리그지역', -- 공통코드
    LGUE_NAME VARCHAR(30) NOT NULL COMMENT '리그명',
    LGUE_NKNM VARCHAR(30) COMMENT '리그별명',
    LGUE_ST_DATE CHAR(8) COMMENT '리그시작일시',
    LGUE_ED_DATE CHAR(8) COMMENT '리그종료일시',
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_LGUE_PK PRIMARY KEY(LGUE_NO),
    INDEX HY_LGUE_IDX1 (LGUE_GRUP)
 ) COMMENT 'HY 리그';
 
 ALTER TABLE HY_LGUE AUTO_INCREMENT = 100000;

DESC HY_LGUE;
SHOW INDEX FROM HY_LGUE;

SELECT * FROM HY_LGUE;