-- 테이블 삭제
 DROP TABLE IF EXISTS HY_MTCH_PRO;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_MTCH_PRO
 (
	MTCH_PRO_SEQ INT NOT NULL AUTO_INCREMENT COMMENT '매치 선수 SEQ',
    MTCH_NO INT NOT NULL COMMENT '매치번호',
    MTCH_DTAL_NO TINYINT NOT NULL COMMENT '매치상세번호',
    PRO_NO INT NOT NULL COMMENT '선수번호',
    CHMP_NO INT NOT NULL COMMENT '챔피언번호',
    PSTN_TYPE VARCHAR(20) NOT NULL COMMENT '포지션타입', -- 공통코드
    KILL_PIT SMALLINT COMMENT 'KILL POINT',
    DETH_PIT SMALLINT COMMENT 'DEATH POINT',
    ASST_PIT SMALLINT COMMENT 'ASSIST POINT',
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_MTCH_PRO_PK PRIMARY KEY(MTCH_PRO_SEQ),
    INDEX HY_MTCH_PRO_IDX1 (MTCH_NO, MTCH_DTAL_NO),
    INDEX HY_MTCH_PRO_IDX2 (PRO_NO),
    INDEX HY_MTCH_PRO_IDX3 (CHMP_NO)
 ) COMMENT 'HY 매치별 선수 정보';
 
 ALTER TABLE HY_MTCH_PRO AUTO_INCREMENT = 100000;

DESC HY_MTCH_PRO;
SHOW INDEX FROM HY_MTCH_PRO;

SELECT * FROM HY_MTCH_PRO;