-- 테이블 삭제
 DROP TABLE IF EXISTS HY_MTCH;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_MTCH
 (
	MTCH_NO INT NOT NULL AUTO_INCREMENT COMMENT '매치번호',
    LGUE_NO INT NOT NULL COMMENT '리그번호',
    MTCH_TYPE VARCHAR(20) NOT NULL COMMENT '매치타입', -- 공통코드
    MTCH_WIN_TYPE VARCHAR(20) NOT NULL COMMENT '매치승리타입', -- 공통코드
    HOME_TEAM_NO INT NOT NULL COMMENT 'HOME 팀번호',
    AWAY_TEAM_NO INT NOT NULL COMMENT 'AWAY 팀번호',
    LGUE_DATE CHAR(8) NOT NULL COMMENT '리그일시',
    LGUE_TIME CHAR(4) NOT NULL COMMENT '리그시각',
    LGUE_RSLT CHAR(1) COMMENT '리그결과', -- 공통코드
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_LGUE_PK PRIMARY KEY(MTCH_NO),
    INDEX HY_LGUE_IDX1 (LGUE_NO),
    INDEX HY_LGUE_IDX2 (HOME_TEAM_NO),
    INDEX HY_LGUE_IDX3 (AWAY_TEAM_NO),
    INDEX HY_LGUE_IDX4 (LGUE_DATE, LGUE_TIME)
 ) COMMENT 'HY 리그 매치';
 
 ALTER TABLE HY_MTCH AUTO_INCREMENT = 200000;

DESC HY_MTCH;
SHOW INDEX FROM HY_MTCH;

SELECT * FROM HY_MTCH;