-- 테이블 삭제
 DROP TABLE IF EXISTS HY_RPO;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_RPO
 (
	RPO_NO INT NOT NULL AUTO_INCREMENT COMMENT '선수번호',
    PRO_ID VARCHAR(20) NOT NULL COMMENT '선수ID',
    PRO_NAME VARCHAR(20) NOT NULL COMMENT '선수명',
    BRTH_DATE CHAR(8) COMMENT '생일',
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_RPO_PK PRIMARY KEY(RPO_NO)
 ) COMMENT 'HY 선수';
 
 ALTER TABLE HY_RPO AUTO_INCREMENT = 500000;

DESC HY_RPO;
SHOW INDEX FROM HY_RPO;

SELECT * FROM HY_RPO;