-- 테이블 삭제
 DROP TABLE IF EXISTS HY_RPO_HIST;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_RPO_HIST
 (
	RPO_HIST_SEQ INT NOT NULL AUTO_INCREMENT COMMENT '선수이력 SEQ',
    PRO_NO INT NOT NULL COMMENT '선수번호',
    PRO_HIST_NO SMALLINT NOT NULL COMMENT '선수이력번호',
    LGUE_NO INT COMMENT '리그번호',
    TEAM_NO INT COMMENT '팀번호',
    PSTN_TYPE VARCHAR(20) COMMENT '포지션타입', -- 공통코드
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_RPO_HIST_PK PRIMARY KEY(RPO_HIST_SEQ),
    INDEX HY_RPO_HIST_IDX1 (PRO_NO)
 ) COMMENT 'HY 선수이력';
 
 ALTER TABLE HY_RPO_HIST AUTO_INCREMENT = 100000;

DESC HY_RPO_HIST;
SHOW INDEX FROM HY_RPO_HIST;

SELECT * FROM HY_RPO_HIST;