-- 테이블 삭제
 DROP TABLE IF EXISTS HY_RPO_ATCH;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_RPO_ATCH
 (
	RPO_ATCH_SEQ INT NOT NULL AUTO_INCREMENT COMMENT '선수첨부파일 SEQ',
    PRO_NO INT NOT NULL COMMENT '선수번호',
    PRO_ATCH_NO TINYINT NOT NULL COMMENT '선수첨부파일번호',
    FILE_TYPE VARCHAR(20) NOT NULL COMMENT '파일타입', -- 공통코드
    FILE_PATH VARCHAR(500) NOT NULL COMMENT '파일경로',
    LGUE_NO INT COMMENT '리그번호',
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_RPO_ATCH_PK PRIMARY KEY(RPO_ATCH_SEQ),
    INDEX HY_RPO_ATCH_IDX1 (PRO_NO)
 ) COMMENT 'HY 선수첨부파일';
 
 ALTER TABLE HY_RPO_ATCH AUTO_INCREMENT = 100000;

DESC HY_RPO_ATCH;
SHOW INDEX FROM HY_RPO_ATCH;

SELECT * FROM HY_RPO_ATCH;