-- 테이블 삭제
 DROP TABLE IF EXISTS HY_TEAM_HIST;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_TEAM_HIST
 (
	TEAM_HIST_SEQ INT NOT NULL AUTO_INCREMENT COMMENT '팀이력 SEQ',
    TEAM_NO INT NOT NULL COMMENT '팀번호',
    TEAM_HIST_NO SMALLINT NOT NULL COMMENT '팀이력번호',
    LGUE_NO INT COMMENT '리그번호',
    TEAM_SPON VARCHAR(50) COMMENT '팀스폰서',
    TEAM_FULL_NAME VARCHAR(50) COMMENT '팀 풀네임',
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_TEAM_HIST_PK PRIMARY KEY(TEAM_HIST_SEQ),
    INDEX HY_TEAM_HIST_IDX1 (TEAM_NO)
 ) COMMENT 'HY 팀이력';
 
 ALTER TABLE HY_TEAM_HIST AUTO_INCREMENT = 100000;

DESC HY_TEAM_HIST;
SHOW INDEX FROM HY_TEAM_HIST;

SELECT * FROM HY_TEAM_HIST;