-- 테이블 삭제
 DROP TABLE IF EXISTS HY_TEAM;
 
 -- 테이블 및 인덱스 생성
 CREATE TABLE HY_TEAM
 (
	TEAM_NO INT NOT NULL AUTO_INCREMENT COMMENT '팀번호',
    TEAM_NAME VARCHAR(20) NOT NULL COMMENT '팀명',
    TEAM_NKNM VARCHAR(20) COMMENT '팀별명',
    TEAM_ABBR VARCHAR(20) NOT NULL COMMENT '팀약어',
    LGUE_GRUP VARCHAR(20) NOT NULL COMMENT '리그지역', -- 공통코드
    FUND_DATE CHAR(8) COMMENT '팀 창단일',
    DB_STAT CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'DB상태', -- 공통코드
    CONSTRAINT HY_TEAM_PK PRIMARY KEY(TEAM_NO),
    INDEX HY_TEAM_IDX1 (LGUE_GRUP)
 ) COMMENT 'HY 팀';
 
 ALTER TABLE HY_TEAM AUTO_INCREMENT = 600000;

DESC HY_TEAM;
SHOW INDEX FROM HY_TEAM;

SELECT * FROM HY_TEAM;